version: '3.8'

services:
  training:
    build:
      context: .
      dockerfile: Datasets-Dockerfile
    container_name: dataset-experiment-container
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    volumes:
      - ../data:/workspace/data
      - ./model_store:/workspace/source/model_store

    # Optional environment variables
    environment:
      PYTHONUNBUFFERED: 1