version: '3.8'  # You can specify a different version if needed

services:
  training:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: training_container
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    volumes:
      - ../data:/workspace/data
      - ./model_store:/workspace/source/model_store

    # Optional environment variables
    environment:
      PYTHONUNBUFFERED: 1
      # Used to change training
      USE_BRUSH: 1
      NORMALIZE_COORDS: 0
      USE_PREDICTION_TOKEN: 0
      USE_LSTM: 0
      LSTM_MODEL_PATH: "path/to/model"

      BATCH_SIZE: 32
      PATCHES_DIM: "16, 16"
      EMBEDDING_DIMS: 256
      IMAGE_MAX_SHAPE: "112, 112"

      N_EPOCHS: 10
      LR: 0.0005
      DatasetName: "dataset"

      WEIGHT_COORD: 1.0
      WEIGHT_SKELETON: 1.0

      ENCODER_HEADS: 8
      DECODER_HEADS: 8

      ENCODER_LAYERS: 12
      DECODER_LAYERS: 12
      AUTOREGRESS_TARGET_LEN: 500
      MAKE_POSITIONAL_ENCODING_LEARNABLE: 1