version: '3.8'

services:
  training:
    build:
      context: .
      dockerfile: RayTune-Dockerfile-Hyperparams
    container_name: raytune_container_hyperparams
    
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

    volumes:
      - ../data:/workspace/data
      - ./model_store:/workspace/source/model_store
      - ./raytune_results:/home/ubuntu/ray_results/

    # Optional environment variables
    environment:
      PYTHONUNBUFFERED: 1